PS C:\Users\TNT\Downloads> python .\temp_chamber_test.py
Traceback (most recent call last):
  File ".\temp_chamber_test.py", line 1, in <module>
    import pyvisa
ImportError: No module named pyvisa
PS C:\Users\TNT\Downloads> pip install pyvisa
Requirement already satisfied: pyvisa in c:\users\tnt\appdata\local\programs\python\python311\lib\site-packages (1.14.1)
Requirement already satisfied: typing-extensions in c:\users\tnt\appdata\local\programs\python\python311\lib\site-packages (from pyvisa) (4.12.2)

[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: C:\Users\TNT\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip
PS C:\Users\TNT\Downloads> pip install pyvisa-py
Requirement already satisfied: pyvisa-py in c:\users\tnt\appdata\local\programs\python\python311\lib\site-packages (0.7.2)
Requirement already satisfied: pyvisa>=1.13.0 in c:\users\tnt\appdata\local\programs\python\python311\lib\site-packages (from pyvisa-py) (1.14.1)
Requirement already satisfied: typing-extensions in c:\users\tnt\appdata\local\programs\python\python311\lib\site-packages (from pyvisa-py) (4.12.2)

[notice] A new release of pip is available: 23.2.1 -> 24.1.2
[notice] To update, run: C:\Users\TNT\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip
PS C:\Users\TNT\Downloads> python .\temp_chamber_test.py
Traceback (most recent call last):
  File ".\temp_chamber_test.py", line 1, in <module>
    import pyvisa
ImportError: No module named pyvisa
